import React from 'react';
import { useForm } from 'react-hook-form';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PasswordInput } from '@/components/ui/password-input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { 
  Loader2, 
  User, 
  Mail, 
  IdCard, 
  GraduationCap, 
  Calendar, 
  Phone, 
  Shield, 
  Lock,
  Users,
  BookOpen,
  Hash
} from 'lucide-react';
import { api } from '@/integrations/api/client';

interface StudentFormProps {
  onSubmit: (data: StudentFormData) => void;
  initialData?: StudentFormData;
  isLoading?: boolean;
}

export interface StudentFormData {
  id?: string;
  full_name: string;
  student_id?: string;  // Optional - will be auto-generated by backend
  email: string;
  faculty_id: number;
  semester: number;
  year: number;
  batch: number;
  phone_number?: string;
  emergency_contact?: string;
  password?: string;
  confirmPassword?: string;
}

const StudentForm = ({ onSubmit, initialData, isLoading = false }: StudentFormProps) => {
  const { register, handleSubmit, formState: { errors }, reset, watch, setValue } = useForm<StudentFormData>({
    defaultValues: initialData || {
      full_name: '',
      student_id: '',
      email: '',
      faculty_id: 0,
      semester: 1,
      year: 1,
      batch: new Date().getFullYear(),
    },
  });
  const { toast } = useToast();
  const [previewStudentId, setPreviewStudentId] = React.useState<string>('');

  // Fetch faculties for dropdown
  const { data: faculties = [] } = useQuery({
    queryKey: ['faculties'],
    queryFn: () => api.faculties.getAll(),
  });

  // Auto-set year based on semester
  const semester = watch('semester');
  React.useEffect(() => {
    let year = 1;
    if (semester === 1 || semester === 2) year = 1;
    else if (semester === 3 || semester === 4) year = 2;
    else if (semester === 5 || semester === 6) year = 3;
    else if (semester === 7 || semester === 8) year = 4;
    setValue('year', year, { shouldValidate: true });
  }, [semester, setValue]);

  // Watch faculty and batch to generate preview ID
  const watchedFacultyId = watch('faculty_id');
  const watchedBatch = watch('batch');

  React.useEffect(() => {
    if (!initialData && watchedFacultyId && watchedBatch) {
      const selectedFaculty = faculties.find((f: any) => f.id === Number(watchedFacultyId));
      if (selectedFaculty && selectedFaculty.code) {
        // Use the faculty code directly from the database!
        const preview = `${selectedFaculty.code}${watchedBatch}XXX`;
        setPreviewStudentId(preview);
      }
    } else if (!initialData) {
      setPreviewStudentId('');
    }
  }, [watchedFacultyId, watchedBatch, faculties, initialData]);

  const handleFormSubmit = (data: StudentFormData) => {
    onSubmit(data);
    if (!initialData) {
      reset();
    }
  };

  return (
    <div className="w-full">
      <div className="max-w-5xl mx-auto">
        <Card className="border border-slate-200/80 dark:border-slate-700/50 shadow-sm bg-white/95 dark:bg-slate-900/95 backdrop-blur-sm overflow-hidden">
          <CardHeader className="border-b border-slate-100 dark:border-slate-800 bg-gradient-to-r from-slate-50 to-slate-100/50 dark:from-slate-800/50 dark:to-slate-900/50 px-8 py-6">
            <div className="flex items-start gap-4">
              <div className="p-3 bg-blue-500/10 dark:bg-blue-500/20 rounded-xl border border-blue-500/20 transition-all duration-300 hover:scale-105 hover:bg-blue-500/15">
                <User className="h-6 w-6 text-blue-600 dark:text-blue-400" />
              </div>
              <div className="flex-1">
                <CardTitle className="text-2xl font-semibold text-slate-900 dark:text-slate-50 tracking-tight">
                  {initialData ? 'Edit Student Profile' : 'Add New Student'}
                </CardTitle>
                <CardDescription className="text-slate-600 dark:text-slate-400 mt-1.5 leading-relaxed">
                  {initialData 
                    ? 'Update student information and academic details.' 
                    : 'Fill in the required information to create a new student profile.'}
                </CardDescription>
              </div>
            </div>
          </CardHeader>
          
          <form onSubmit={handleSubmit(handleFormSubmit)}>
            <CardContent className="px-8 py-6 space-y-8">
              
              {/* Personal Information Section */}
              <div className="space-y-5">
                <div className="flex items-center gap-3 pb-3 border-b border-slate-200/60 dark:border-slate-700/60">
                  <div className="p-2 bg-blue-50 dark:bg-blue-900/30 rounded-lg">
                    <User className="h-4 w-4 text-blue-600 dark:text-blue-400" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-base font-semibold text-slate-900 dark:text-slate-50">Personal Information</h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Basic student details</p>
                  </div>
                  <Badge variant="secondary" className="bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 border-0 text-xs font-medium">Required</Badge>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div className="space-y-2 group">
                    <Label htmlFor="full_name" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <User className="h-3.5 w-3.5 text-slate-400" />
                      Full Name
                    </Label>
                    <Input 
                      id="full_name" 
                      {...register('full_name', { required: "Full name is required" })} 
                      placeholder="e.g. John Doe" 
                      disabled={isLoading}
                      className="h-11 border-slate-200 dark:border-slate-700 focus:border-blue-500 dark:focus:border-blue-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                    />
                    {errors.full_name && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.full_name.message}
                    </span>}
                  </div>
                  
                  <div className="space-y-2 group">
                    <Label htmlFor="email" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <Mail className="h-3.5 w-3.5 text-slate-400" />
                      Email Address
                    </Label>
                    <Input 
                      id="email" 
                      type="email" 
                      {...register('email', { 
                        required: "Email is required",
                        pattern: {
                          value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                          message: "Invalid email address"
                        }
                      })} 
                      placeholder="e.g. john.doe@college.edu" 
                      disabled={isLoading}
                      className="h-11 border-slate-200 dark:border-slate-700 focus:border-blue-500 dark:focus:border-blue-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                    />
                    {errors.email && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.email.message}
                    </span>}
                  </div>
                </div>
              </div>

              {/* Academic Information Section */}
              <div className="space-y-5">
                <div className="flex items-center gap-3 pb-3 border-b border-slate-200/60 dark:border-slate-700/60">
                  <div className="p-2 bg-purple-50 dark:bg-purple-900/30 rounded-lg">
                    <GraduationCap className="h-4 w-4 text-purple-600 dark:text-purple-400" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-base font-semibold text-slate-900 dark:text-slate-50">Academic Information</h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Student ID and enrollment details</p>
                  </div>
                  <Badge variant="secondary" className="bg-purple-50 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 border-0 text-xs font-medium">Required</Badge>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div className="space-y-2">
                    <Label htmlFor="student_id" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <IdCard className="h-3.5 w-3.5 text-slate-400" />
                      Student ID
                      {!initialData && (
                        <Badge variant="outline" className="ml-auto border-purple-200 dark:border-purple-800 text-purple-700 dark:text-purple-300 text-xs font-medium">
                          Auto-generated
                        </Badge>
                      )}
                    </Label>
                    <div className="relative">
                      <Input 
                        id="student_id" 
                        {...register('student_id')} 
                        value={initialData?.student_id || previewStudentId}
                        placeholder={initialData ? "e.g. CSCI2025001" : "Select faculty to preview ID..."}
                        readOnly
                        disabled={isLoading}
                        className="h-11 border-slate-200 dark:border-slate-700 transition-colors duration-200 bg-slate-100/50 dark:bg-slate-800/80 text-slate-700 dark:text-slate-300 placeholder:text-slate-400 dark:placeholder:text-slate-500 cursor-not-allowed font-mono font-semibold text-base tracking-wide"
                      />
                      {!initialData && previewStudentId && (
                        <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-1.5">
                          <div className="flex gap-0.5">
                            <span className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-pulse"></span>
                            <span className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-pulse" style={{ animationDelay: '0.2s' }}></span>
                            <span className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-pulse" style={{ animationDelay: '0.4s' }}></span>
                          </div>
                          <span className="text-xs text-purple-600 dark:text-purple-400 font-medium">Preview</span>
                        </div>
                      )}
                    </div>
                    {!initialData && previewStudentId && (
                      <p className="text-xs text-purple-600 dark:text-purple-400 flex items-center gap-1.5 mt-1 font-medium">
                        <span className="w-1 h-1 bg-purple-500 rounded-full animate-pulse"></span>
                        Preview ID format (XXX will be replaced with sequence number)
                      </p>
                    )}
                    {!initialData && !previewStudentId && (
                      <p className="text-xs text-slate-500 dark:text-slate-400 flex items-center gap-1.5 mt-1">
                        <span className="w-1 h-1 bg-slate-400 rounded-full"></span>
                        Select faculty and batch year to see ID preview
                      </p>
                    )}
                    {errors.student_id && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.student_id.message}
                    </span>}
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="faculty_id" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <GraduationCap className="h-3.5 w-3.5 text-slate-400" />
                      Faculty
                    </Label>
                    <select 
                      id="faculty_id" 
                      {...register('faculty_id', { 
                        required: "Faculty is required",
                        valueAsNumber: true,
                        validate: value => value > 0 || "Please select a faculty"
                      })} 
                      className="flex h-11 w-full rounded-md border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-3 py-2 text-sm focus:border-purple-500 dark:focus:border-purple-400 focus:outline-none focus:ring-2 focus:ring-purple-500/20 transition-colors duration-200 disabled:cursor-not-allowed disabled:opacity-50"
                      disabled={isLoading}
                    >
                      <option value="">Select Faculty</option>
                      {faculties.map((faculty: { id: number; name: string }) => (
                        <option key={faculty.id} value={faculty.id}>
                          {faculty.name}
                        </option>
                      ))}
                    </select>
                    {errors.faculty_id && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.faculty_id.message}
                    </span>}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                  <div className="space-y-2">
                    <Label htmlFor="semester" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <BookOpen className="h-3.5 w-3.5 text-slate-400" />
                      Semester
                    </Label>
                    <Input 
                      id="semester" 
                      type="number" 
                      min="1" 
                      max="8" 
                      {...register('semester', { 
                        required: "Semester is required",
                        valueAsNumber: true,
                        min: {
                          value: 1,
                          message: "Semester must be at least 1"
                        },
                        max: {
                          value: 8,
                          message: "Semester cannot be more than 8"
                        }
                      })} 
                      placeholder="1" 
                      disabled={isLoading}
                      className="h-11 border-slate-200 dark:border-slate-700 focus:border-purple-500 dark:focus:border-purple-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                    />
                    {errors.semester && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.semester.message}
                    </span>}
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="year" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <Calendar className="h-3.5 w-3.5 text-slate-400" />
                      Academic Year
                    </Label>
                    <Input 
                      id="year" 
                      type="number" 
                      min="1" 
                      max="4" 
                      {...register('year', { 
                        required: "Academic year is required",
                        valueAsNumber: true,
                        min: {
                          value: 1,
                          message: "Year must be at least 1"
                        },
                        max: {
                          value: 4,
                          message: "Year cannot be more than 4"
                        }
                      })} 
                      placeholder="1" 
                      readOnly
                      disabled={isLoading}
                      className="h-11 bg-slate-50 dark:bg-slate-800/50 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400"
                    />
                    {errors.year && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.year.message}
                    </span>}
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="batch" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <Users className="h-3.5 w-3.5 text-slate-400" />
                      Batch Year
                    </Label>
                    <Input 
                      id="batch" 
                      type="number" 
                      min="2020" 
                      max={new Date().getFullYear() + 1}
                      {...register('batch', { 
                        required: "Batch year is required",
                        valueAsNumber: true,
                        min: {
                          value: 2020,
                          message: "Batch year must be at least 2020"
                        },
                        max: {
                          value: new Date().getFullYear() + 1,
                          message: `Batch year cannot be more than ${new Date().getFullYear() + 1}`
                        }
                      })} 
                      placeholder={new Date().getFullYear().toString()}
                      disabled={isLoading}
                      className="h-11 border-slate-200 dark:border-slate-700 focus:border-purple-500 dark:focus:border-purple-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                    />
                    {errors.batch && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.batch.message}
                    </span>}
                  </div>
                </div>
              </div>

              {/* Contact Information Section */}
              <div className="space-y-5">
                <div className="flex items-center gap-3 pb-3 border-b border-slate-200/60 dark:border-slate-700/60">
                  <div className="p-2 bg-emerald-50 dark:bg-emerald-900/30 rounded-lg">
                    <Phone className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-base font-semibold text-slate-900 dark:text-slate-50">Contact Information</h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Phone numbers for communication</p>
                  </div>
                  <Badge variant="outline" className="border-emerald-200 dark:border-emerald-800 text-emerald-700 dark:text-emerald-300 text-xs font-medium">Optional</Badge>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div className="space-y-2">
                    <Label htmlFor="phone_number" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <Phone className="h-3.5 w-3.5 text-slate-400" />
                      Phone Number
                    </Label>
                    <Input 
                      id="phone_number" 
                      type="tel"
                      {...register('phone_number')} 
                      placeholder="e.g. +977-9812345678" 
                      disabled={isLoading}
                      className="h-11 border-slate-200 dark:border-slate-700 focus:border-emerald-500 dark:focus:border-emerald-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                    />
                    {errors.phone_number && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.phone_number.message}
                    </span>}
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="emergency_contact" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                      <Shield className="h-3.5 w-3.5 text-slate-400" />
                      Emergency Contact
                    </Label>
                    <Input 
                      id="emergency_contact" 
                      type="tel"
                      {...register('emergency_contact')} 
                      placeholder="e.g. +977-9887654321" 
                      disabled={isLoading}
                      className="h-11 border-slate-200 dark:border-slate-700 focus:border-emerald-500 dark:focus:border-emerald-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                    />
                    {errors.emergency_contact && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                      <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                      {errors.emergency_contact.message}
                    </span>}
                  </div>
                </div>
              </div>
              
              {/* Security Section - Password fields only shown when creating a new student */}
              {!initialData && (
                <div className="space-y-5">
                  <div className="flex items-center gap-3 pb-3 border-b border-slate-200/60 dark:border-slate-700/60">
                    <div className="p-2 bg-rose-50 dark:bg-rose-900/30 rounded-lg">
                      <Lock className="h-4 w-4 text-rose-600 dark:text-rose-400" />
                    </div>
                    <div className="flex-1">
                      <h3 className="text-base font-semibold text-slate-900 dark:text-slate-50">Security</h3>
                      <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Account password credentials</p>
                    </div>
                    <Badge variant="secondary" className="bg-rose-50 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300 border-0 text-xs font-medium">Required</Badge>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div className="space-y-2">
                      <Label htmlFor="password" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                        <Lock className="h-3.5 w-3.5 text-slate-400" />
                        Password
                      </Label>
                      <PasswordInput 
                        id="password" 
                        {...register('password', { 
                          required: initialData ? false : "Password is required",
                          minLength: {
                            value: 8,
                            message: "Password must be at least 8 characters"
                          }
                        })} 
                        placeholder="••••••••" 
                        disabled={isLoading}
                        className="h-11 border-slate-200 dark:border-slate-700 focus:border-rose-500 dark:focus:border-rose-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                      />
                      {errors.password && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                        <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                        {errors.password.message}
                      </span>}
                    </div>
                    
                    <div className="space-y-2">
                      <Label htmlFor="confirmPassword" className="text-sm font-medium text-slate-700 dark:text-slate-300 flex items-center gap-2">
                        <Lock className="h-3.5 w-3.5 text-slate-400" />
                        Confirm Password
                      </Label>
                      <PasswordInput 
                        id="confirmPassword" 
                        {...register('confirmPassword', { 
                          required: initialData ? false : "Please confirm password",
                          validate: (value, formValues) => 
                            value === formValues.password || "Passwords do not match"
                        })} 
                        placeholder="••••••••" 
                        disabled={isLoading}
                        className="h-11 border-slate-200 dark:border-slate-700 focus:border-rose-500 dark:focus:border-rose-400 transition-colors duration-200 bg-white dark:bg-slate-800"
                      />
                      {errors.confirmPassword && <span className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1.5 mt-1">
                        <span className="w-1 h-1 bg-red-600 dark:bg-red-400 rounded-full"></span>
                        {errors.confirmPassword.message}
                      </span>}
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
            
            <CardFooter className="bg-slate-50/80 dark:bg-slate-800/80 border-t border-slate-200/60 dark:border-slate-700/60 px-8 py-5">
              <div className="flex justify-between items-center w-full">
                <Button 
                  type="button" 
                  variant="outline" 
                  onClick={() => reset()} 
                  disabled={isLoading}
                  className="px-5 border-slate-300 dark:border-slate-600 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors duration-200"
                >
                  Reset Form
                </Button>
                <Button 
                  type="submit" 
                  disabled={isLoading}
                  className="px-8 bg-blue-600 hover:bg-blue-700 dark:bg-blue-600 dark:hover:bg-blue-700 transition-all duration-200 shadow-sm hover:shadow-md"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      {initialData ? 'Updating...' : 'Creating...'}
                    </>
                  ) : (
                    <>
                      <User className="mr-2 h-4 w-4" />
                      {initialData ? 'Update Student' : 'Create Student'}
                    </>
                  )}
                </Button>
              </div>
            </CardFooter>
          </form>
        </Card>
      </div>
    </div>
  );
};

export default StudentForm;
