import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Search, X, Users2, Plus, Edit, Trash2, Eye, Loader2, GraduationCap, Settings, Calendar, Copy } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { api } from '@/integrations/api/client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';

interface Teacher {
  id: number;
  teacher_id: string;
  name: string;
  user: {
    id: number;
    email: string;
    full_name: string;
    role: string;
  };
  faculty_id?: number;
  department?: string;
  phone_number?: string;
  office_location?: string;
  created_at: string;
}

interface Faculty {
  id: number;
  name: string;
  code: string;
  description?: string;
}

interface TeacherFormData {
  full_name: string;
  email: string;
  password?: string;
  confirmPassword?: string;
  teacher_id?: string; // auto-generated by server on create
  faculty_id?: number;
  department?: string;
  phone_number?: string;
  office_location?: string;
}

interface TeacherAssignment {
  id: number;
  subject_id: number;
  subject_name: string;
  subject_code: string;
  faculty_id: number;
  faculty_name: string;
  semester: number;
  day_of_week: string;
  start_time: string;
  end_time: string;
  classroom?: string;
  academic_year: number;
  student_count?: number;
  time_slot_display: string;
}

const TeachersPage = () => {
  const [activeTab, setActiveTab] = useState<string>('list');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [selectedFaculty, setSelectedFaculty] = useState<string>('all');
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isManageDialogOpen, setIsManageDialogOpen] = useState(false);
  const [isAddAssignmentDialogOpen, setIsAddAssignmentDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [selectedTeacher, setSelectedTeacher] = useState<Teacher | null>(null);
  const [assignmentSearchQuery, setAssignmentSearchQuery] = useState<string>('');
  const [filterFacultyId, setFilterFacultyId] = useState<string>('all');
  const [filterSemester, setFilterSemester] = useState<string>('all');
  const [filterSubjectId, setFilterSubjectId] = useState<string>('all');
  
  // Add/Edit form subject assignment filters
  const [formFilterFacultyId, setFormFilterFacultyId] = useState<string>('all');
  const [formFilterSemester, setFormFilterSemester] = useState<string>('all');
  const [selectedSubjectIds, setSelectedSubjectIds] = useState<number[]>([]);
  const [formData, setFormData] = useState<TeacherFormData>({
    full_name: '',
    email: '',
    password: '',
    confirmPassword: '',
    teacher_id: undefined,
    faculty_id: undefined,
    department: '',
    phone_number: '',
    office_location: '',
  });
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch teachers
  const { data: teachers = [], isLoading, refetch } = useQuery({
    queryKey: ['teachers', selectedFaculty],
    queryFn: async () => {
      const facultyId = selectedFaculty !== 'all' ? parseInt(selectedFaculty) : undefined;
      return await api.teachers.getAll(facultyId);
    },
  });

  // Fetch faculties for dropdown
  const { data: faculties = [] } = useQuery({
    queryKey: ['faculties'],
    queryFn: () => api.faculties.getAll(),
  });

  // Subjects list for filters in Add Assignment (depends on faculty and optional semester)
  const { data: filterSubjects = [] } = useQuery({
    queryKey: ['subjects-by-faculty-semester', filterFacultyId, filterSemester],
    queryFn: async () => {
      if (filterFacultyId === 'all') return [] as any[];
      const fid = parseInt(filterFacultyId);
      const sem = filterSemester !== 'all' ? parseInt(filterSemester) : undefined;
      return await api.subjects.getByFacultySemester(fid, sem);
    },
    enabled: isAddAssignmentDialogOpen && filterFacultyId !== 'all',
  });

  // Subjects for form assignment (Add/Edit dialogs) - grouped by unique subject
  const { data: formSubjects = [] } = useQuery({
    queryKey: ['form-subjects', formFilterFacultyId, formFilterSemester],
    queryFn: async () => {
      if (formFilterFacultyId === 'all') return [] as any[];
      const fid = parseInt(formFilterFacultyId);
      const sem = formFilterSemester !== 'all' ? parseInt(formFilterSemester) : undefined;
      return await api.subjects.getByFacultySemester(fid, sem);
    },
    enabled: (isAddDialogOpen || isEditDialogOpen) && formFilterFacultyId !== 'all',
    refetchOnWindowFocus: false,
    refetchOnMount: false,
    refetchOnReconnect: false,
  });

  // Fetch assignments for selected teacher
  const { data: assignments = [], refetch: refetchAssignments } = useQuery({
    queryKey: ['teacher-assignments', selectedTeacher?.id],
    queryFn: async () => {
      if (!selectedTeacher) return [];
      return await api.teachers.getAssignments(selectedTeacher.id);
    },
    enabled: !!selectedTeacher && isManageDialogOpen,
  });

  // Fetch unassigned schedules
  const { data: unassignedSchedules = [] } = useQuery({
    queryKey: ['unassigned-schedules', filterFacultyId, filterSemester],
    queryFn: () => api.teachers.getUnassignedSchedules(
      filterFacultyId !== 'all' ? parseInt(filterFacultyId) : undefined,
      filterSemester !== 'all' ? parseInt(filterSemester) : undefined
    ),
    enabled: isAddAssignmentDialogOpen,
  });

  // Create teacher mutation
  const createTeacherMutation = useMutation({
    mutationFn: async (data: TeacherFormData) => {
      if (!data.password) {
        throw new Error('Password is required');
      }
      if (data.password !== data.confirmPassword) {
        throw new Error('Passwords do not match');
      }
      const created = await api.teachers.create({
        user: {
          email: data.email,
          full_name: data.full_name,
          password: data.password,
        },
        name: data.full_name,
        faculty_id: data.faculty_id,
        // department removed from UI in favor of faculty dropdown
        phone_number: data.phone_number,
        office_location: data.office_location,
      });
      return created;
    },
    onSuccess: async (newTeacher) => {
      // Assign all schedules for selected subjects
      if (selectedSubjectIds.length > 0) {
        try {
          // Get all unassigned schedules for the selected subjects
          const allSchedules = await api.schedules.getAll({ is_active: true });
          const schedulesToAssign = allSchedules.filter((s: any) => 
            selectedSubjectIds.includes(s.subject_id) && !s.teacher_id
          );
          
          await Promise.all(
            schedulesToAssign.map((schedule: any) =>
              api.teachers.addAssignment(newTeacher.id, schedule.id)
            )
          );
        } catch (err) {
          console.error('Failed to assign some subjects:', err);
        }
      }
      
      toast({
        title: 'Success',
        description: 'Teacher created successfully',
      });
      setIsAddDialogOpen(false);
      resetForm();
      queryClient.invalidateQueries({ queryKey: ['teachers'] });
    },
    onError: (error: unknown) => {
      const err = error as { message?: string };
      toast({
        title: 'Error',
        description: err.message || 'Failed to create teacher',
        variant: 'destructive',
      });
    },
  });

  // Update teacher mutation
  const updateTeacherMutation = useMutation({
    mutationFn: async ({ id, data }: { id: number; data: Partial<TeacherFormData> }) => {
      return await api.teachers.update(id, {
        faculty_id: data.faculty_id,
        // department removed from UI in favor of faculty dropdown
        phone_number: data.phone_number,
        office_location: data.office_location,
      });
    },
    onSuccess: async (_, variables) => {
      // Sync subject assignments
      if (selectedTeacher) {
        try {
          // Fetch current assignments
          const currentAssignments = await api.teachers.getAssignments(selectedTeacher.id);
          const currentSubjectIds = [...new Set(currentAssignments.map((a: any) => a.subject_id))];
          
          // Find subjects to remove (unchecked)
          const subjectsToRemove = currentSubjectIds.filter((sid: number) => !selectedSubjectIds.includes(sid));
          const schedulesToRemove = currentAssignments.filter((a: any) => subjectsToRemove.includes(a.subject_id));
          await Promise.all(
            schedulesToRemove.map((a: any) =>
              api.teachers.removeAssignment(selectedTeacher.id, a.id)
            )
          );
          
          // Find subjects to add (newly checked)
          const subjectsToAdd = selectedSubjectIds.filter(sid => !currentSubjectIds.includes(sid));
          if (subjectsToAdd.length > 0) {
            // Get all unassigned schedules for new subjects
            const allSchedules = await api.schedules.getAll({ is_active: true });
            const schedulesToAdd = allSchedules.filter((s: any) => 
              subjectsToAdd.includes(s.subject_id) && !s.teacher_id
            );
            await Promise.all(
              schedulesToAdd.map((schedule: any) =>
                api.teachers.addAssignment(selectedTeacher.id, schedule.id)
              )
            );
          }
        } catch (err) {
          console.error('Failed to sync assignments:', err);
        }
      }
      
      toast({
        title: 'Success',
        description: 'Teacher updated successfully',
      });
      setIsEditDialogOpen(false);
      setSelectedTeacher(null);
      queryClient.invalidateQueries({ queryKey: ['teachers'] });
    },
    onError: (error: unknown) => {
      const err = error as { message?: string };
      toast({
        title: 'Error',
        description: err.message || 'Failed to update teacher',
        variant: 'destructive',
      });
    },
  });

  // Delete teacher mutation
  const deleteTeacherMutation = useMutation({
    mutationFn: async (id: number) => {
      return await api.teachers.delete(id);
    },
    onSuccess: () => {
      toast({
        title: 'Success',
        description: 'Teacher deleted successfully',
      });
      setIsDeleteDialogOpen(false);
      setSelectedTeacher(null);
      queryClient.invalidateQueries({ queryKey: ['teachers'] });
    },
    onError: (error: unknown) => {
      const err = error as { message?: string };
      toast({
        title: 'Error',
        description: err.message || 'Failed to delete teacher',
        variant: 'destructive',
      });
    },
  });

  // Add assignment mutation
  const addAssignmentMutation = useMutation({
    mutationFn: async ({ teacherId, scheduleId }: { teacherId: number; scheduleId: number }) => {
      return await api.teachers.addAssignment(teacherId, scheduleId);
    },
    onSuccess: () => {
      toast({
        title: 'Success',
        description: 'Subject assigned to teacher successfully',
      });
      setIsAddAssignmentDialogOpen(false);
      refetchAssignments();
      queryClient.invalidateQueries({ queryKey: ['unassigned-schedules'] });
    },
    onError: (error: unknown) => {
      const err = error as { message?: string };
      toast({
        title: 'Error',
        description: err.message || 'Failed to assign subject',
        variant: 'destructive',
      });
    },
  });

  // Remove assignment mutation
  const removeAssignmentMutation = useMutation({
    mutationFn: async ({ teacherId, scheduleId }: { teacherId: number; scheduleId: number }) => {
      return await api.teachers.removeAssignment(teacherId, scheduleId);
    },
    onSuccess: () => {
      toast({
        title: 'Success',
        description: 'Subject assignment removed successfully',
      });
      refetchAssignments();
      queryClient.invalidateQueries({ queryKey: ['unassigned-schedules'] });
    },
    onError: (error: unknown) => {
      const err = error as { message?: string };
      toast({
        title: 'Error',
        description: err.message || 'Failed to remove assignment',
        variant: 'destructive',
      });
    },
  });

  // Filter teachers
  const filteredTeachers = React.useMemo(() => {
    return teachers.filter((teacher: Teacher) => {
      const query = searchQuery.toLowerCase();
      return (
        teacher.name?.toLowerCase().includes(query) ||
        teacher.teacher_id?.toLowerCase().includes(query) ||
        teacher.user?.email?.toLowerCase().includes(query) ||
        teacher.department?.toLowerCase().includes(query)
      );
    });
  }, [teachers, searchQuery]);

  const resetForm = () => {
    setFormData({
      full_name: '',
      email: '',
      password: '',
      confirmPassword: '',
      teacher_id: undefined,
      faculty_id: undefined,
      department: '',
      phone_number: '',
      office_location: '',
    });
    setFormFilterFacultyId('all');
    setFormFilterSemester('all');
    setSelectedSubjectIds([]);
  };

  const handleAddTeacher = () => {
    resetForm();
    setIsAddDialogOpen(true);
  };

  const handleEditTeacher = async (teacher: Teacher) => {
    setSelectedTeacher(teacher);
    setFormData({
      full_name: teacher.name,
      email: teacher.user.email,
      teacher_id: teacher.teacher_id, // read-only display in Edit
      faculty_id: teacher.faculty_id,
      department: teacher.department || '',
      phone_number: teacher.phone_number || '',
      office_location: teacher.office_location || '',
    });
    setFormFilterFacultyId('all');
    setFormFilterSemester('all');
    
    // Fetch current assignments and extract unique subject IDs
    try {
      const currentAssignments = await api.teachers.getAssignments(teacher.id);
      const uniqueSubjectIds = [...new Set(currentAssignments.map((a: any) => a.subject_id))];
      setSelectedSubjectIds(uniqueSubjectIds);
    } catch (err) {
      console.error('Failed to fetch assignments:', err);
      setSelectedSubjectIds([]);
    }
    
    setIsEditDialogOpen(true);
  };

  const handleManageAssignments = (teacher: Teacher) => {
    setSelectedTeacher(teacher);
    setAssignmentSearchQuery('');
    setIsManageDialogOpen(true);
  };

  const handleAddAssignment = () => {
    setIsAddAssignmentDialogOpen(true);
  };

  const handleAssignToSchedule = (scheduleId: number) => {
    if (selectedTeacher) {
      addAssignmentMutation.mutate({
        teacherId: selectedTeacher.id,
        scheduleId,
      });
    }
  };

  const handleRemoveAssignment = (scheduleId: number) => {
    if (selectedTeacher) {
      removeAssignmentMutation.mutate({
        teacherId: selectedTeacher.id,
        scheduleId,
      });
    }
  };

  const handleDeleteTeacher = (teacher: Teacher) => {
    setSelectedTeacher(teacher);
    setIsDeleteDialogOpen(true);
  };

  const handleSubmitCreate = () => {
    createTeacherMutation.mutate(formData);
  };

  const handleSubmitEdit = () => {
    if (selectedTeacher) {
      updateTeacherMutation.mutate({
        id: selectedTeacher.id,
        data: formData,
      });
    }
  };

  const handleSubmitDelete = () => {
    if (selectedTeacher) {
      deleteTeacherMutation.mutate(selectedTeacher.id);
    }
  };

  // Group unassigned schedules by subject and filter
  const groupedUnassignedSubjects = React.useMemo(() => {
    if (!Array.isArray(unassignedSchedules)) return [];
    
    // First filter by search and subject
    const filtered = unassignedSchedules.filter((schedule: TeacherAssignment) => {
      if (filterSubjectId !== 'all' && schedule.subject_id !== parseInt(filterSubjectId)) {
        return false;
      }
      const query = assignmentSearchQuery.toLowerCase();
      return (
        schedule.subject_name?.toLowerCase().includes(query) ||
        schedule.subject_code?.toLowerCase().includes(query) ||
        schedule.faculty_name?.toLowerCase().includes(query)
      );
    });

    // Group by subject_id
    const grouped = filtered.reduce((acc: any, schedule: TeacherAssignment) => {
      const key = schedule.subject_id;
      if (!acc[key]) {
        acc[key] = {
          subject_id: schedule.subject_id,
          subject_name: schedule.subject_name,
          subject_code: schedule.subject_code,
          faculty_name: schedule.faculty_name,
          semester: schedule.semester,
          scheduleCount: 0,
          schedules: [],
        };
      }
      acc[key].scheduleCount++;
      acc[key].schedules.push(schedule);
      return acc;
    }, {});

    return Object.values(grouped);
  }, [unassignedSchedules, assignmentSearchQuery, filterSubjectId]);

  const getFacultyName = (facultyId?: number) => {
    const faculty = (faculties as Faculty[]).find((f) => f.id === facultyId);
    return faculty?.name || 'N/A';
  };

  // Group current assignments by subject for a cleaner Manage view
  const groupedAssignments = React.useMemo(() => {
    if (!Array.isArray(assignments)) return [] as Array<{
      subject_id: number;
      subject_name: string;
      subject_code: string;
      faculty_name: string;
      semester: number;
      schedules: TeacherAssignment[];
    }>;

    const grouped = assignments.reduce((acc: any, a: TeacherAssignment) => {
      const key = a.subject_id;
      if (!acc[key]) {
        acc[key] = {
          subject_id: a.subject_id,
          subject_name: a.subject_name,
          subject_code: a.subject_code,
          faculty_name: a.faculty_name,
          semester: a.semester,
          schedules: [] as TeacherAssignment[],
        };
      }
      acc[key].schedules.push(a);
      return acc;
    }, {} as Record<number, any>);

    return Object.values(grouped);
  }, [assignments]);

  // Track which subjects are expanded to show their sessions
  const [expandedSubjectIds, setExpandedSubjectIds] = useState<number[]>([]);
  const toggleSubjectExpand = (subjectId: number) => {
    setExpandedSubjectIds((prev) =>
      prev.includes(subjectId) ? prev.filter((id) => id !== subjectId) : [...prev, subjectId]
    );
  };

  // Remove all sessions for a subject
  const handleRemoveAllForSubject = async (subjectId: number) => {
    if (!selectedTeacher) return;
    const toRemove = assignments.filter((a: TeacherAssignment) => a.subject_id === subjectId);
    if (toRemove.length === 0) return;

    let success = 0;
    let failed = 0;
    for (const a of toRemove) {
      try {
        // Call API directly to avoid spamming per-item toasts from the mutation
        await api.teachers.removeAssignment(selectedTeacher.id, a.id);
        success++;
      } catch (err) {
        console.error('Failed to remove assignment', a.id, err);
        failed++;
      }
    }

    await refetchAssignments();
    queryClient.invalidateQueries({ queryKey: ['unassigned-schedules'] });

    toast({
      title: failed > 0 ? 'Partial removal' : 'Removed',
      description: failed > 0
        ? `Removed ${success} session(s). ${failed} failed.`
        : `Removed ${success} session(s).`,
      variant: failed > 0 ? 'destructive' : undefined,
    });
  };

  // Assign any missing sessions for a subject (assign all unassigned schedules for this subject)
  const [assignAllLoadingSubjectId, setAssignAllLoadingSubjectId] = useState<number | null>(null);
  const handleAssignAllForSubject = async (subjectId: number) => {
    if (!selectedTeacher) return;
    try {
      setAssignAllLoadingSubjectId(subjectId);
      // Fetch all schedules and assign those for this subject that are unassigned
      const allSchedules = await api.schedules.getAll({ is_active: true });
      const allSubjectSchedules = (allSchedules as any[]).filter((s: any) => s.subject_id === subjectId);
      const toAssign = allSubjectSchedules.filter((s: any) => !s.teacher_id);
      const conflicts = allSubjectSchedules.filter((s: any) => s.teacher_id && s.teacher_id !== selectedTeacher.id).length;
      const alreadyMine = allSubjectSchedules.filter((s: any) => s.teacher_id === selectedTeacher.id).length;

      if (toAssign.length === 0) {
        const msg = conflicts > 0
          ? `No new sessions assigned. ${conflicts} session(s) belong to another teacher, ${alreadyMine} already assigned to this teacher.`
          : 'All sessions for this subject are already assigned to this teacher.';
        toast({ title: 'No action needed', description: msg });
        return;
      }

      for (const s of toAssign) {
        await api.teachers.addAssignment(selectedTeacher.id, s.id);
      }

      const desc = conflicts > 0
        ? `Assigned ${toAssign.length} session(s) to ${selectedTeacher.name}. ${conflicts} conflicted session(s) were skipped.`
        : `Assigned ${toAssign.length} session(s) to ${selectedTeacher.name}.`;
      toast({ title: 'Assigned', description: desc });
      await refetchAssignments();
      queryClient.invalidateQueries({ queryKey: ['unassigned-schedules'] });
    } catch (err) {
      console.error('Assign all failed', err);
      toast({ title: 'Error', description: 'Failed to assign all sessions', variant: 'destructive' });
    } finally {
      setAssignAllLoadingSubjectId(null);
    }
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-white flex items-center gap-2">
            <Users2 className="w-8 h-8" />
            Teachers Management
          </h1>
          <p className="text-slate-400 mt-1">
            Manage teacher accounts, assignments, and information
          </p>
        </div>
        <Button onClick={handleAddTeacher} className="bg-blue-600 hover:bg-blue-700">
          <Plus className="w-4 h-4 mr-2" />
          Add Teacher
        </Button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="bg-slate-900/70 border-slate-700/80">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs font-medium text-slate-400 uppercase">Total Teachers</p>
                <h3 className="text-3xl font-bold text-white">{teachers.length}</h3>
              </div>
              <Users2 className="w-10 h-10 text-blue-400" />
            </div>
          </CardContent>
        </Card>
        <Card className="bg-slate-900/70 border-slate-700/80">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs font-medium text-slate-400 uppercase">Faculties</p>
                <h3 className="text-3xl font-bold text-white">{faculties.length}</h3>
              </div>
              <GraduationCap className="w-10 h-10 text-emerald-400" />
            </div>
          </CardContent>
        </Card>
        <Card className="bg-slate-900/70 border-slate-700/80">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs font-medium text-slate-400 uppercase">Filtered Results</p>
                <h3 className="text-3xl font-bold text-white">{filteredTeachers.length}</h3>
              </div>
              <Search className="w-10 h-10 text-amber-400" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card className="bg-slate-900/70 border-slate-700/80">
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <Input
                placeholder="Search by name, teacher ID, email, or department..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10 bg-slate-800 border-slate-700 text-white"
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery('')}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white"
                >
                  <X className="w-4 h-4" />
                </button>
              )}
            </div>
            <Select value={selectedFaculty} onValueChange={setSelectedFaculty}>
              <SelectTrigger className="w-[200px] bg-slate-800 border-slate-700 text-white">
                <SelectValue placeholder="All Faculties" />
              </SelectTrigger>
              <SelectContent className="bg-slate-900 border-slate-700 text-white">
                <SelectItem value="all">All Faculties</SelectItem>
                {(faculties as Faculty[]).map((faculty) => (
                  <SelectItem key={faculty.id} value={faculty.id.toString()}>
                    {faculty.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Teachers Table */}
      <Card className="bg-slate-900/70 border-slate-700/80">
        <CardHeader>
          <CardTitle className="text-white">Teachers List</CardTitle>
          <CardDescription className="text-slate-400">
            {filteredTeachers.length} teacher{filteredTeachers.length !== 1 ? 's' : ''} found
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-blue-400" />
            </div>
          ) : filteredTeachers.length === 0 ? (
            <div className="text-center py-12 text-slate-400">
              <Users2 className="w-12 h-12 mx-auto mb-2 opacity-50" />
              <p>No teachers found</p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow className="border-slate-800">
                  <TableHead className="text-slate-300">Teacher ID</TableHead>
                  <TableHead className="text-slate-300">Name</TableHead>
                  <TableHead className="text-slate-300">Email</TableHead>
                  <TableHead className="text-slate-300">Faculty</TableHead>
                  <TableHead className="text-slate-300">Department</TableHead>
                  <TableHead className="text-slate-300">Phone</TableHead>
                  <TableHead className="text-slate-300">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredTeachers.map((teacher: Teacher) => (
                  <TableRow key={teacher.id} className="border-slate-800 hover:bg-slate-800/50">
                    <TableCell className="text-white font-mono">{teacher.teacher_id}</TableCell>
                    <TableCell className="text-white">{teacher.name}</TableCell>
                    <TableCell className="text-slate-300">{teacher.user.email}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className="bg-slate-700/50 text-slate-200 border-slate-600/50">
                        {getFacultyName(teacher.faculty_id)}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-slate-300">{teacher.department || 'N/A'}</TableCell>
                    <TableCell className="text-slate-300">{teacher.phone_number || 'N/A'}</TableCell>
                    <TableCell>
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleManageAssignments(teacher)}
                          className="border-blue-600 text-blue-400 hover:bg-blue-900/30"
                          title="Manage Subject Assignments"
                        >
                          <Settings className="w-3 h-3" />
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleEditTeacher(teacher)}
                          className="border-slate-600 text-slate-200 hover:bg-slate-700"
                          title="Edit Personal Information"
                        >
                          <Edit className="w-3 h-3" />
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleDeleteTeacher(teacher)}
                          className="border-red-600 text-red-400 hover:bg-red-900/30"
                          title="Delete Teacher"
                        >
                          <Trash2 className="w-3 h-3" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Add Teacher Dialog */}
      <Dialog 
        open={isAddDialogOpen} 
        onOpenChange={(open) => {
          // Only allow closing when mutation is not pending
          if (!open && !createTeacherMutation.isPending) {
            setIsAddDialogOpen(false);
          } else if (open) {
            setIsAddDialogOpen(true);
          }
        }}
      >
        <DialogContent
          className="bg-slate-900 border-slate-700 text-white max-w-2xl"
          onEscapeKeyDown={(e) => e.preventDefault()}
          onInteractOutside={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle>Add New Teacher</DialogTitle>
            <DialogDescription className="text-slate-400">
              Create a new teacher account with login credentials
            </DialogDescription>
          </DialogHeader>
          <div className="grid grid-cols-2 gap-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="full_name">Full Name *</Label>
              <Input
                id="full_name"
                value={formData.full_name}
                onChange={(e) => setFormData({ ...formData, full_name: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
              />
            </div>
            {/* Teacher ID is auto-generated on create */}
            <div className="space-y-2">
              <Label className="text-slate-300">Teacher ID</Label>
              <div className="text-slate-400 text-sm">Will be generated automatically</div>
            </div>
            <div className="space-y-2 col-span-2">
              <Label htmlFor="email">Email *</Label>
              <Input
                id="email"
                type="email"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password *</Label>
              <Input
                id="password"
                type="password"
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="confirmPassword">Confirm Password *</Label>
              <Input
                id="confirmPassword"
                type="password"
                value={formData.confirmPassword}
                onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
              />
            </div>
            <div className="space-y-2">
              <Label className="text-slate-300">Faculty</Label>
              <Select
                value={formData.faculty_id ? formData.faculty_id.toString() : ''}
                onValueChange={(v) => setFormData({ ...formData, faculty_id: v ? parseInt(v) : undefined })}
              >
                <SelectTrigger className="bg-slate-800 border-slate-700 text-white">
                  <SelectValue placeholder="Select faculty" />
                </SelectTrigger>
                <SelectContent className="bg-slate-900 border-slate-700 text-white">
                  {(faculties as Faculty[]).map((f) => (
                    <SelectItem key={f.id} value={f.id.toString()}>
                      {f.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone_number">Phone Number (Optional)</Label>
              <Input
                id="phone_number"
                value={formData.phone_number}
                onChange={(e) => setFormData({ ...formData, phone_number: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
                placeholder="e.g., +1-555-0100"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="office_location">Office Location (Optional)</Label>
              <Input
                id="office_location"
                value={formData.office_location}
                onChange={(e) => setFormData({ ...formData, office_location: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
                placeholder="e.g., Room 301, Building A"
              />
            </div>
            
            {/* Subject Assignment Section */}
            <div className="col-span-2 pt-4 border-t border-slate-700">
              <h3 className="text-sm font-semibold text-white mb-3">Assign Subjects (Optional)</h3>
              <div className="grid grid-cols-2 gap-3 mb-3">
                <div>
                  <Label className="text-slate-300 text-xs">Faculty</Label>
                  <Select value={formFilterFacultyId} onValueChange={(v) => { setFormFilterFacultyId(v); setFormFilterSemester('all'); }}>
                    <SelectTrigger className="bg-slate-800 border-slate-700 text-white text-sm mt-1">
                      <SelectValue placeholder="Select faculty" />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-900 border-slate-700 text-white">
                      <SelectItem value="all">Select faculty first</SelectItem>
                      {(faculties as Faculty[]).map((f) => (
                        <SelectItem key={f.id} value={f.id.toString()}>{f.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-slate-300 text-xs">Semester</Label>
                  <Select value={formFilterSemester} onValueChange={setFormFilterSemester} disabled={formFilterFacultyId === 'all'}>
                    <SelectTrigger className="bg-slate-800 border-slate-700 text-white text-sm mt-1 disabled:opacity-50">
                      <SelectValue placeholder="All semesters" />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-900 border-slate-700 text-white">
                      <SelectItem value="all">All Semesters</SelectItem>
                      {[1,2,3,4,5,6,7,8].map((s) => (
                        <SelectItem key={s} value={s.toString()}>Semester {s}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              {formFilterFacultyId !== 'all' && (
                <div className="max-h-[200px] overflow-y-auto bg-slate-800/50 rounded border border-slate-700 p-2">
                  {(formSubjects as any[]).length === 0 ? (
                    <p className="text-slate-400 text-sm text-center py-4">No subjects found</p>
                  ) : (
                    <div className="space-y-1">
                      {(formSubjects as any[]).map((subject: any) => (
                        <label key={subject.id} className="flex items-start gap-2 p-2 hover:bg-slate-700/50 rounded cursor-pointer">
                          <input
                            type="checkbox"
                            checked={selectedSubjectIds.includes(subject.id)}
                            onChange={(e) => {
                              if (e.target.checked) {
                                setSelectedSubjectIds([...selectedSubjectIds, subject.id]);
                              } else {
                                setSelectedSubjectIds(selectedSubjectIds.filter(id => id !== subject.id));
                              }
                            }}
                            className="mt-1"
                          />
                          <div className="flex-1 text-sm">
                            <div className="text-white font-medium">{subject.name} <span className="text-slate-400">({subject.code})</span></div>
                            <div className="text-xs text-slate-400">
                              {subject.credits} credits • {subject.description || 'No description'}
                            </div>
                          </div>
                        </label>
                      ))}
                    </div>
                  )}
                </div>
              )}
              {selectedSubjectIds.length > 0 && (
                <p className="text-xs text-blue-400 mt-2">{selectedSubjectIds.length} subject(s) selected</p>
              )}
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsAddDialogOpen(false)}
              className="border-slate-700 text-slate-300"
            >
              Cancel
            </Button>
            <Button
              onClick={handleSubmitCreate}
              disabled={createTeacherMutation.isPending}
              className="bg-blue-600 hover:bg-blue-700"
            >
              {createTeacherMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Creating...
                </>
              ) : (
                'Create Teacher'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Teacher Dialog */}
      <Dialog 
        open={isEditDialogOpen} 
        onOpenChange={(open) => {
          // Only allow closing when mutation is not pending
          if (!open && !updateTeacherMutation.isPending) {
            setIsEditDialogOpen(false);
          } else if (open) {
            setIsEditDialogOpen(true);
          }
        }}
      >
        <DialogContent
          className="bg-slate-900 border-slate-700 text-white max-w-2xl"
          onEscapeKeyDown={(e) => e.preventDefault()}
          onInteractOutside={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle>Edit Teacher Profile</DialogTitle>
            <DialogDescription className="text-slate-400">
              Update personal information (does not affect teaching assignments)
            </DialogDescription>
          </DialogHeader>
          <div className="grid grid-cols-2 gap-4 py-4">
            <div className="space-y-2 col-span-2">
              <Label>Teacher ID (Read-only)</Label>
              <div className="flex gap-2">
                <Input value={formData.teacher_id} disabled readOnly className="bg-slate-800/50 border-slate-700 text-slate-400" />
                <Button
                  type="button"
                  variant="outline"
                  className="border-slate-700 text-slate-300"
                  onClick={() => {
                    if (formData.teacher_id) {
                      navigator.clipboard.writeText(formData.teacher_id);
                      toast({ title: 'Copied', description: 'Teacher ID copied to clipboard' });
                    }
                  }}
                  title="Copy Teacher ID"
                >
                  <Copy className="w-4 h-4" />
                </Button>
              </div>
            </div>
            <div className="space-y-2 col-span-2">
              <Label>Email (Read-only)</Label>
              <Input value={formData.email} disabled className="bg-slate-800/50 border-slate-700 text-slate-400" />
            </div>
            <div className="space-y-2">
              <Label className="text-slate-300">Faculty</Label>
              <Select
                value={formData.faculty_id ? formData.faculty_id.toString() : ''}
                onValueChange={(v) => setFormData({ ...formData, faculty_id: v ? parseInt(v) : undefined })}
              >
                <SelectTrigger className="bg-slate-800 border-slate-700 text-white">
                  <SelectValue placeholder="Select faculty" />
                </SelectTrigger>
                <SelectContent className="bg-slate-900 border-slate-700 text-white">
                  {(faculties as Faculty[]).map((f) => (
                    <SelectItem key={f.id} value={f.id.toString()}>
                      {f.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="edit_phone_number">Phone Number (Optional)</Label>
              <Input
                id="edit_phone_number"
                value={formData.phone_number}
                onChange={(e) => setFormData({ ...formData, phone_number: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
                placeholder="e.g., +1-555-0100"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="edit_office_location">Office Location (Optional)</Label>
              <Input
                id="edit_office_location"
                value={formData.office_location}
                onChange={(e) => setFormData({ ...formData, office_location: e.target.value })}
                className="bg-slate-800 border-slate-700 text-white"
                placeholder="e.g., Room 301, Building A"
              />
            </div>
            
            {/* Subject Assignment Section */}
            <div className="col-span-2 pt-4 border-t border-slate-700">
              <h3 className="text-sm font-semibold text-white mb-3">Manage Subject Assignments</h3>
              <div className="grid grid-cols-2 gap-3 mb-3">
                <div>
                  <Label className="text-slate-300 text-xs">Faculty</Label>
                  <Select value={formFilterFacultyId} onValueChange={(v) => { setFormFilterFacultyId(v); setFormFilterSemester('all'); }}>
                    <SelectTrigger className="bg-slate-800 border-slate-700 text-white text-sm mt-1">
                      <SelectValue placeholder="Select faculty" />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-900 border-slate-700 text-white">
                      <SelectItem value="all">Select faculty first</SelectItem>
                      {(faculties as Faculty[]).map((f) => (
                        <SelectItem key={f.id} value={f.id.toString()}>{f.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-slate-300 text-xs">Semester</Label>
                  <Select value={formFilterSemester} onValueChange={setFormFilterSemester} disabled={formFilterFacultyId === 'all'}>
                    <SelectTrigger className="bg-slate-800 border-slate-700 text-white text-sm mt-1 disabled:opacity-50">
                      <SelectValue placeholder="All semesters" />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-900 border-slate-700 text-white">
                      <SelectItem value="all">All Semesters</SelectItem>
                      {[1,2,3,4,5,6,7,8].map((s) => (
                        <SelectItem key={s} value={s.toString()}>Semester {s}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              {formFilterFacultyId !== 'all' && (
                <div className="max-h-[200px] overflow-y-auto bg-slate-800/50 rounded border border-slate-700 p-2">
                  {(formSubjects as any[]).length === 0 ? (
                    <p className="text-slate-400 text-sm text-center py-4">No subjects found</p>
                  ) : (
                    <div className="space-y-1">
                      {(formSubjects as any[]).map((subject: any) => (
                        <label key={subject.id} className="flex items-start gap-2 p-2 hover:bg-slate-700/50 rounded cursor-pointer">
                          <input
                            type="checkbox"
                            checked={selectedSubjectIds.includes(subject.id)}
                            onChange={(e) => {
                              if (e.target.checked) {
                                setSelectedSubjectIds([...selectedSubjectIds, subject.id]);
                              } else {
                                setSelectedSubjectIds(selectedSubjectIds.filter(id => id !== subject.id));
                              }
                            }}
                            className="mt-1"
                          />
                          <div className="flex-1 text-sm">
                            <div className="text-white font-medium">{subject.name} <span className="text-slate-400">({subject.code})</span></div>
                            <div className="text-xs text-slate-400">
                              {subject.credits} credits • {subject.description || 'No description'}
                            </div>
                          </div>
                        </label>
                      ))}
                    </div>
                  )}
                </div>
              )}
              {selectedSubjectIds.length > 0 && (
                <p className="text-xs text-blue-400 mt-2">{selectedSubjectIds.length} subject(s) selected</p>
              )}
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
              className="border-slate-700 text-slate-300"
            >
              Cancel
            </Button>
            <Button
              onClick={handleSubmitEdit}
              disabled={updateTeacherMutation.isPending}
              className="bg-blue-600 hover:bg-blue-700"
            >
              {updateTeacherMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Updating...
                </>
              ) : (
                'Update Teacher'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Manage Subject Assignments Dialog */}
      <Dialog open={isManageDialogOpen} onOpenChange={setIsManageDialogOpen}>
        <DialogContent className="bg-slate-900 border-slate-700 text-white max-w-5xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Manage Subject Assignments - {selectedTeacher?.name}</DialogTitle>
            <DialogDescription className="text-slate-400">
              Assign or remove subjects this teacher will teach
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-4 py-4">
            <div className="flex justify-between items-center">
              <h3 className="text-lg font-semibold text-white">
                Current Assignments ({groupedAssignments.length})
              </h3>
              <Button
                onClick={handleAddAssignment}
                className="bg-blue-600 hover:bg-blue-700"
                size="sm"
              >
                <Plus className="w-4 h-4 mr-2" />
                Add Assignment
              </Button>
            </div>
            
            {groupedAssignments.length === 0 ? (
              <div className="text-center py-12 text-slate-400 bg-slate-800/50 rounded-lg border border-slate-700">
                <Calendar className="w-12 h-12 mx-auto mb-2 opacity-50" />
                <p>No subject assignments yet</p>
                <p className="text-sm mt-1">Click "Add Assignment" to assign subjects to this teacher</p>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow className="border-slate-800">
                    <TableHead className="text-slate-300">Subject</TableHead>
                    <TableHead className="text-slate-300">Faculty</TableHead>
                    <TableHead className="text-slate-300">Semester</TableHead>
                    <TableHead className="text-slate-300">Sessions</TableHead>
                    <TableHead className="text-slate-300">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {groupedAssignments.map((group: any) => (
                    <React.Fragment key={group.subject_id}>
                      <TableRow className="border-slate-800 hover:bg-slate-800/50">
                        <TableCell className="text-white">
                          <div>
                            <div className="font-medium">{group.subject_name}</div>
                            <div className="text-xs text-slate-400">{group.subject_code}</div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline" className="bg-slate-700/50 text-slate-200 border-slate-600/50">
                            {group.faculty_name}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-slate-300">Semester {group.semester}</TableCell>
                        <TableCell className="text-slate-300">
                          <Badge variant="outline" className="bg-blue-900/30 text-blue-400 border-blue-700/50">
                            {group.schedules.length} session(s)
                          </Badge>
                        </TableCell>
                        <TableCell className="space-x-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => toggleSubjectExpand(group.subject_id)}
                            className="border-slate-600 text-slate-200"
                          >
                            {expandedSubjectIds.includes(group.subject_id) ? 'Hide sessions' : 'View sessions'}
                          </Button>
                          <Button
                            size="sm"
                            onClick={() => handleAssignAllForSubject(group.subject_id)}
                            disabled={assignAllLoadingSubjectId === group.subject_id}
                            className="bg-blue-600 hover:bg-blue-700 text-white"
                          >
                            {assignAllLoadingSubjectId === group.subject_id ? (
                              <Loader2 className="w-3 h-3 animate-spin" />
                            ) : (
                              'Assign All'
                            )}
                          </Button>
                          <Button
                            size="sm"
                            variant="destructive"
                            onClick={() => handleRemoveAllForSubject(group.subject_id)}
                            disabled={removeAssignmentMutation.isPending}
                          >
                            {removeAssignmentMutation.isPending ? (
                              <Loader2 className="w-3 h-3 animate-spin" />
                            ) : (
                              'Remove All'
                            )}
                          </Button>
                        </TableCell>
                      </TableRow>
                      {expandedSubjectIds.includes(group.subject_id) && (
                        <TableRow className="bg-slate-900/40">
                          <TableCell colSpan={5} className="p-0">
                            <div className="p-3">
                              <Table>
                                <TableHeader>
                                  <TableRow className="border-slate-800">
                                    <TableHead className="text-slate-300">Schedule</TableHead>
                                    <TableHead className="text-slate-300">Classroom</TableHead>
                                    <TableHead className="text-slate-300">Students</TableHead>
                                    <TableHead className="text-slate-300">Actions</TableHead>
                                  </TableRow>
                                </TableHeader>
                                <TableBody>
                                  {group.schedules.map((assignment: TeacherAssignment) => (
                                    <TableRow key={assignment.id} className="border-slate-800 hover:bg-slate-800/50">
                                      <TableCell className="text-slate-300">
                                        <div>
                                          <div className="font-medium">{assignment.day_of_week}</div>
                                          <div className="text-xs text-slate-400">{assignment.time_slot_display}</div>
                                        </div>
                                      </TableCell>
                                      <TableCell className="text-slate-300">
                                        {assignment.classroom || <span className="text-slate-500">N/A</span>}
                                      </TableCell>
                                      <TableCell className="text-slate-300">
                                        <Badge variant="outline" className="bg-blue-900/30 text-blue-400 border-blue-700/50">
                                          {assignment.student_count || 0} students
                                        </Badge>
                                      </TableCell>
                                      <TableCell>
                                        <Button
                                          size="sm"
                                          variant="destructive"
                                          onClick={() => handleRemoveAssignment(assignment.id)}
                                          disabled={removeAssignmentMutation.isPending}
                                        >
                                          {removeAssignmentMutation.isPending ? (
                                            <Loader2 className="w-3 h-3 animate-spin" />
                                          ) : (
                                            <X className="w-3 h-3" />
                                          )}
                                        </Button>
                                      </TableCell>
                                    </TableRow>
                                  ))}
                                </TableBody>
                              </Table>
                            </div>
                          </TableCell>
                        </TableRow>
                      )}
                    </React.Fragment>
                  ))}
                </TableBody>
              </Table>
            )}
          </div>
          
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setIsManageDialogOpen(false);
                setSelectedTeacher(null);
              }}
              className="border-slate-700 text-slate-300"
            >
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Add Assignment Dialog */}
      <Dialog open={isAddAssignmentDialogOpen} onOpenChange={setIsAddAssignmentDialogOpen}>
        <DialogContent className="bg-slate-900 border-slate-700 text-white max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add Subject Assignment</DialogTitle>
            <DialogDescription className="text-slate-400">
              Select subjects to assign to {selectedTeacher?.name}. All class sessions for each subject will be assigned.
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-4 py-4">
            {/* Cascading filters: Faculty -> Semester -> Subject */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              <div>
                <Label className="text-slate-300">Faculty</Label>
                <Select value={filterFacultyId} onValueChange={(v) => { setFilterFacultyId(v); setFilterSemester('all'); setFilterSubjectId('all'); }}>
                  <SelectTrigger className="bg-slate-800 border-slate-700 text-white mt-1">
                    <SelectValue placeholder="Select faculty" />
                  </SelectTrigger>
                  <SelectContent className="bg-slate-900 border-slate-700 text-white">
                    <SelectItem value="all">All</SelectItem>
                    {(faculties as Faculty[]).map((f) => (
                      <SelectItem key={f.id} value={f.id.toString()}>{f.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-slate-300">Semester</Label>
                <Select value={filterSemester} onValueChange={(v) => { setFilterSemester(v); setFilterSubjectId('all'); }} disabled={filterFacultyId === 'all'}>
                  <SelectTrigger className="bg-slate-800 border-slate-700 text-white mt-1 disabled:opacity-50">
                    <SelectValue placeholder="Select semester" />
                  </SelectTrigger>
                  <SelectContent className="bg-slate-900 border-slate-700 text-white">
                    <SelectItem value="all">All</SelectItem>
                    {[1,2,3,4,5,6,7,8].map((s) => (
                      <SelectItem key={s} value={s.toString()}>Semester {s}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-slate-300">Subject</Label>
                <Select value={filterSubjectId} onValueChange={setFilterSubjectId} disabled={filterFacultyId === 'all'}>
                  <SelectTrigger className="bg-slate-800 border-slate-700 text-white mt-1 disabled:opacity-50">
                    <SelectValue placeholder="Filter by subject" />
                  </SelectTrigger>
                  <SelectContent className="bg-slate-900 border-slate-700 text-white">
                    <SelectItem value="all">All</SelectItem>
                    {(filterSubjects as any[]).map((s: any) => (
                      <SelectItem key={s.id} value={s.id.toString()}>{s.name}{s.code ? ` (${s.code})` : ''}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <Input
                placeholder="Search by subject name, code, or faculty..."
                value={assignmentSearchQuery}
                onChange={(e) => setAssignmentSearchQuery(e.target.value)}
                className="pl-10 bg-slate-800 border-slate-700 text-white"
              />
              {assignmentSearchQuery && (
                <button
                  onClick={() => setAssignmentSearchQuery('')}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white"
                >
                  <X className="w-4 h-4" />
                </button>
              )}
            </div>
            
            {groupedUnassignedSubjects.length === 0 ? (
              <div className="text-center py-12 text-slate-400 bg-slate-800/50 rounded-lg border border-slate-700">
                <Calendar className="w-12 h-12 mx-auto mb-2 opacity-50" />
                <p>No unassigned subjects found</p>
                <p className="text-sm mt-1">All subjects are currently assigned to teachers</p>
              </div>
            ) : (
              <div className="max-h-[400px] overflow-y-auto">
                <Table>
                  <TableHeader className="sticky top-0 bg-slate-900 z-10">
                    <TableRow className="border-slate-800">
                      <TableHead className="text-slate-300">Subject</TableHead>
                      <TableHead className="text-slate-300">Faculty</TableHead>
                      <TableHead className="text-slate-300">Semester</TableHead>
                      <TableHead className="text-slate-300">Class Sessions</TableHead>
                      <TableHead className="text-slate-300">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {groupedUnassignedSubjects.map((subject: any) => (
                      <TableRow key={subject.subject_id} className="border-slate-800 hover:bg-slate-800/50">
                        <TableCell className="text-white">
                          <div>
                            <div className="font-medium">{subject.subject_name}</div>
                            <div className="text-xs text-slate-400">{subject.subject_code}</div>
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline" className="bg-slate-700/50 text-slate-200 border-slate-600/50">
                            {subject.faculty_name}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-slate-300">Semester {subject.semester}</TableCell>
                        <TableCell className="text-slate-300">
                          <div className="flex items-center gap-1">
                            <Calendar className="w-3 h-3 text-slate-400" />
                            <span className="text-xs">{subject.scheduleCount} session(s)</span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <Button
                            size="sm"
                            onClick={() => {
                              // Assign ALL schedules for this subject
                              subject.schedules.forEach((schedule: any) => {
                                handleAssignToSchedule(schedule.id);
                              });
                            }}
                            disabled={addAssignmentMutation.isPending}
                            className="bg-blue-600 hover:bg-blue-700 text-white"
                          >
                            {addAssignmentMutation.isPending ? (
                              <Loader2 className="w-3 h-3 animate-spin" />
                            ) : (
                              'Assign All'
                            )}
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </div>
          
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsAddAssignmentDialogOpen(false)}
              className="border-slate-700 text-slate-300"
            >
              Cancel
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <AlertDialogContent className="bg-slate-900 border-slate-700 text-white">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Teacher</AlertDialogTitle>
            <AlertDialogDescription className="text-slate-400">
              Are you sure you want to delete teacher <strong className="text-white">{selectedTeacher?.name}</strong>? This will also delete their user account and cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="bg-slate-800 border-slate-700 text-slate-300 hover:bg-slate-700">
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleSubmitDelete}
              disabled={deleteTeacherMutation.isPending}
              className="bg-red-600 hover:bg-red-700 text-white"
            >
              {deleteTeacherMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Deleting...
                </>
              ) : (
                'Delete Teacher'
              )}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

export default TeachersPage;
